name: Rina G. Singh
favicon: null
layout_spectrum: 0.74131
typography_spectrum: 0.44443
title: 'Life Coach & Mindfulness Teacher'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dfe7e0'
    - '#d2a900'
    - '#ba7600'
    - '#abbc81'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
