name: RinaGSingh
favicon: null
layout_spectrum: 0.47916
typography_spectrum: 0.6103049400262535
title: 'Life Coach & Mindfulness Teacher'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2dfe3'
    - '#1d2b0d'
    - '#7b6848'
    - '#cba184'
    - '#aaf27a'
  brandStrength: 1
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
