name: RinaGSingh
favicon: null
layout_spectrum: 0.52343
typography_spectrum: 1
title: 'Life Coach & Mindfulness Teacher'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c4bcaf'
    - '#bcdc2f'
    - '#a7c950'
    - '#e6d399'
  brandStrength: 0
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
