name: Rina G. Singh
favicon: null
layout_spectrum: 0.74131
typography_spectrum: 0.44443
title: 'Life Coach & Mindfulness Teacher'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ed0803'
    - '#db1b14'
    - '#fa9796'
    - '#ffc8cd'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
