name: Rina G. Singh
favicon: null
layout_spectrum: 0.85416
typography_spectrum: 0.04687
title: 'Life Coach & Mindfulness Teacher'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c4bcaf'
    - '#bcdc2f'
    - '#a7c950'
    - '#e6d399'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
